'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Represents a strongly typed in-memory cache of data.
'''</summary>
<Global.System.Serializable(), _
 Global.System.ComponentModel.DesignerCategoryAttribute("code"), _
 Global.System.ComponentModel.ToolboxItem(True), _
 Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"), _
 Global.System.Xml.Serialization.XmlRootAttribute("dstOversigt"), _
 Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")> _
Partial Public Class dstOversigt
  Inherits Global.System.Data.DataSet

  Private tableviewOversigt As viewOversigtDataTable

  Private _schemaSerializationMode As Global.System.Data.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema

  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
  Public Sub New()
    MyBase.New()
    Me.BeginInit()
    Me.InitClass()
    Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
    AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
    AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
    Me.EndInit()
  End Sub

  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
  Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
    MyBase.New(info, context, False)
    If (Me.IsBinarySerialized(info, context) = True) Then
      Me.InitVars(False)
      Dim schemaChangedHandler1 As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
      AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
      AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
      Return
    End If
    Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)), String)
    If (Me.DetermineSchemaSerializationMode(info, context) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
      Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet()
      ds.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
      If (Not (ds.Tables("viewOversigt")) Is Nothing) Then
        MyBase.Tables.Add(New viewOversigtDataTable(ds.Tables("viewOversigt")))
      End If
      Me.DataSetName = ds.DataSetName
      Me.Prefix = ds.Prefix
      Me.Namespace = ds.Namespace
      Me.Locale = ds.Locale
      Me.CaseSensitive = ds.CaseSensitive
      Me.EnforceConstraints = ds.EnforceConstraints
      Me.Merge(ds, False, Global.System.Data.MissingSchemaAction.Add)
      Me.InitVars()
    Else
      Me.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
    End If
    Me.GetSerializationData(info, context)
    Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
    AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
    AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
  End Sub

  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"), _
   Global.System.ComponentModel.Browsable(False), _
   Global.System.ComponentModel.DesignerSerializationVisibility(Global.System.ComponentModel.DesignerSerializationVisibility.Content)> _
  Public ReadOnly Property viewOversigt() As viewOversigtDataTable
    Get
      Return Me.tableviewOversigt
    End Get
  End Property

  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"), _
   Global.System.ComponentModel.BrowsableAttribute(True), _
   Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Visible)> _
  Public Overrides Property SchemaSerializationMode() As Global.System.Data.SchemaSerializationMode
    Get
      Return Me._schemaSerializationMode
    End Get
    Set(value As Global.System.Data.SchemaSerializationMode)
      Me._schemaSerializationMode = value
    End Set
  End Property

  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"), _
   Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)> _
  Public Shadows ReadOnly Property Tables() As Global.System.Data.DataTableCollection
    Get
      Return MyBase.Tables
    End Get
  End Property

  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"), _
   Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)> _
  Public Shadows ReadOnly Property Relations() As Global.System.Data.DataRelationCollection
    Get
      Return MyBase.Relations
    End Get
  End Property

  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
  Protected Overrides Sub InitializeDerivedDataSet()
    Me.BeginInit()
    Me.InitClass()
    Me.EndInit()
  End Sub

  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
  Public Overrides Function Clone() As Global.System.Data.DataSet
    Dim cln As dstOversigt = CType(MyBase.Clone, dstOversigt)
    cln.InitVars()
    cln.SchemaSerializationMode = Me.SchemaSerializationMode
    Return cln
  End Function

  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
  Protected Overrides Function ShouldSerializeTables() As Boolean
    Return False
  End Function

  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
  Protected Overrides Function ShouldSerializeRelations() As Boolean
    Return False
  End Function

  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
  Protected Overrides Sub ReadXmlSerializable(ByVal reader As Global.System.Xml.XmlReader)
    If (Me.DetermineSchemaSerializationMode(reader) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
      Me.Reset()
      Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet()
      ds.ReadXml(reader)
      If (Not (ds.Tables("viewOversigt")) Is Nothing) Then
        MyBase.Tables.Add(New viewOversigtDataTable(ds.Tables("viewOversigt")))
      End If
      Me.DataSetName = ds.DataSetName
      Me.Prefix = ds.Prefix
      Me.Namespace = ds.Namespace
      Me.Locale = ds.Locale
      Me.CaseSensitive = ds.CaseSensitive
      Me.EnforceConstraints = ds.EnforceConstraints
      Me.Merge(ds, False, Global.System.Data.MissingSchemaAction.Add)
      Me.InitVars()
    Else
      Me.ReadXml(reader)
      Me.InitVars()
    End If
  End Sub

  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
  Protected Overrides Function GetSchemaSerializable() As Global.System.Xml.Schema.XmlSchema
    Dim stream As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
    Me.WriteXmlSchema(New Global.System.Xml.XmlTextWriter(stream, Nothing))
    stream.Position = 0
    Return Global.System.Xml.Schema.XmlSchema.Read(New Global.System.Xml.XmlTextReader(stream), Nothing)
  End Function

  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
  Friend Overloads Sub InitVars()
    Me.InitVars(True)
  End Sub

  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
  Friend Overloads Sub InitVars(ByVal initTable As Boolean)
    Me.tableviewOversigt = CType(MyBase.Tables("viewOversigt"), viewOversigtDataTable)
    If (initTable = True) Then
      If (Not (Me.tableviewOversigt) Is Nothing) Then
        Me.tableviewOversigt.InitVars()
      End If
    End If
  End Sub

  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
  Private Sub InitClass()
    Me.DataSetName = "dstOversigt"
    Me.Prefix = ""
    Me.Namespace = "http://tempuri.org/dstOversigt.xsd"
    Me.EnforceConstraints = True
    Me.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
    Me.tableviewOversigt = New viewOversigtDataTable()
    MyBase.Tables.Add(Me.tableviewOversigt)
  End Sub

  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
  Private Function ShouldSerializeviewOversigt() As Boolean
    Return False
  End Function

  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
  Private Sub SchemaChanged(ByVal sender As Object, ByVal e As Global.System.ComponentModel.CollectionChangeEventArgs)
    If (e.Action = Global.System.ComponentModel.CollectionChangeAction.Remove) Then
      Me.InitVars()
    End If
  End Sub

  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
  Public Shared Function GetTypedDataSetSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
    Dim ds As dstOversigt = New dstOversigt()
    Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType()
    Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence()
    Dim any As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
    any.Namespace = ds.Namespace
    sequence.Items.Add(any)
    type.Particle = sequence
    Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
    If xs.Contains(dsSchema.TargetNamespace) Then
      Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
      Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
      Try
        Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
        dsSchema.Write(s1)
        Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
        Do While schemas.MoveNext
          schema = CType(schemas.Current, Global.System.Xml.Schema.XmlSchema)
          s2.SetLength(0)
          schema.Write(s2)
          If (s1.Length = s2.Length) Then
            s1.Position = 0
            s2.Position = 0

            Do While ((s1.Position <> s1.Length) _
                        AndAlso (s1.ReadByte = s2.ReadByte))


            Loop
            If (s1.Position = s1.Length) Then
              Return type
            End If
          End If

        Loop
      Finally
        If (Not (s1) Is Nothing) Then
          s1.Close()
        End If
        If (Not (s2) Is Nothing) Then
          s2.Close()
        End If
      End Try
    End If
    xs.Add(dsSchema)
    Return type
  End Function

  <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
  Public Delegate Sub viewOversigtRowChangeEventHandler(ByVal sender As Object, ByVal e As viewOversigtRowChangeEvent)

  '''<summary>
  '''Represents the strongly named DataTable class.
  '''</summary>
  <Global.System.Serializable(), _
   Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")> _
  Partial Public Class viewOversigtDataTable
    Inherits Global.System.Data.TypedTableBase(Of viewOversigtRow)

    Private columnMedieplanNr As Global.System.Data.DataColumn

    Private columnVersion As Global.System.Data.DataColumn

    Private columnAnnoncørNo_ As Global.System.Data.DataColumn

    Private columnBureauNo_ As Global.System.Data.DataColumn

    Private columnFormat As Global.System.Data.DataColumn

    Private columnAntalFarver As Global.System.Data.DataColumn

    Private columnIndrykningsUge As Global.System.Data.DataColumn

    Private columnOrdreUdsendt As Global.System.Data.DataColumn

    Private columnMaterialeFra As Global.System.Data.DataColumn

    Private columnMaterialeUdsendt As Global.System.Data.DataColumn

    Private columnOrdreAnsvarlig As Global.System.Data.DataColumn

    Private columnSalgsAnsvarlig As Global.System.Data.DataColumn

    Private columnNr As Global.System.Data.DataColumn

    Private columnOverskrift As Global.System.Data.DataColumn

    Private columnDeadline As Global.System.Data.DataColumn

    Private columnKommentar As Global.System.Data.DataColumn

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Sub New()
      MyBase.New()
      Me.TableName = "viewOversigt"
      Me.BeginInit()
      Me.InitClass()
      Me.EndInit()
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Friend Sub New(ByVal table As Global.System.Data.DataTable)
      MyBase.New()
      Me.TableName = table.TableName
      If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
        Me.CaseSensitive = table.CaseSensitive
      End If
      If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
        Me.Locale = table.Locale
      End If
      If (table.Namespace <> table.DataSet.Namespace) Then
        Me.Namespace = table.Namespace
      End If
      Me.Prefix = table.Prefix
      Me.MinimumCapacity = table.MinimumCapacity
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
      MyBase.New(info, context)
      Me.InitVars()
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public ReadOnly Property MedieplanNrColumn() As Global.System.Data.DataColumn
      Get
        Return Me.columnMedieplanNr
      End Get
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public ReadOnly Property VersionColumn() As Global.System.Data.DataColumn
      Get
        Return Me.columnVersion
      End Get
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public ReadOnly Property AnnoncørNo_Column() As Global.System.Data.DataColumn
      Get
        Return Me.columnAnnoncørNo_
      End Get
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public ReadOnly Property BureauNo_Column() As Global.System.Data.DataColumn
      Get
        Return Me.columnBureauNo_
      End Get
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public ReadOnly Property FormatColumn() As Global.System.Data.DataColumn
      Get
        Return Me.columnFormat
      End Get
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public ReadOnly Property AntalFarverColumn() As Global.System.Data.DataColumn
      Get
        Return Me.columnAntalFarver
      End Get
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public ReadOnly Property IndrykningsUgeColumn() As Global.System.Data.DataColumn
      Get
        Return Me.columnIndrykningsUge
      End Get
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public ReadOnly Property OrdreUdsendtColumn() As Global.System.Data.DataColumn
      Get
        Return Me.columnOrdreUdsendt
      End Get
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public ReadOnly Property MaterialeFraColumn() As Global.System.Data.DataColumn
      Get
        Return Me.columnMaterialeFra
      End Get
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public ReadOnly Property MaterialeUdsendtColumn() As Global.System.Data.DataColumn
      Get
        Return Me.columnMaterialeUdsendt
      End Get
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public ReadOnly Property OrdreAnsvarligColumn() As Global.System.Data.DataColumn
      Get
        Return Me.columnOrdreAnsvarlig
      End Get
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public ReadOnly Property SalgsAnsvarligColumn() As Global.System.Data.DataColumn
      Get
        Return Me.columnSalgsAnsvarlig
      End Get
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public ReadOnly Property NrColumn() As Global.System.Data.DataColumn
      Get
        Return Me.columnNr
      End Get
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public ReadOnly Property OverskriftColumn() As Global.System.Data.DataColumn
      Get
        Return Me.columnOverskrift
      End Get
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public ReadOnly Property DeadlineColumn() As Global.System.Data.DataColumn
      Get
        Return Me.columnDeadline
      End Get
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public ReadOnly Property KommentarColumn() As Global.System.Data.DataColumn
      Get
        Return Me.columnKommentar
      End Get
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"), _
     Global.System.ComponentModel.Browsable(False)> _
    Public ReadOnly Property Count() As Integer
      Get
        Return Me.Rows.Count
      End Get
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Default Public ReadOnly Property Item(ByVal index As Integer) As viewOversigtRow
      Get
        Return CType(Me.Rows(index), viewOversigtRow)
      End Get
    End Property

    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Event viewOversigtRowChanging As viewOversigtRowChangeEventHandler

    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Event viewOversigtRowChanged As viewOversigtRowChangeEventHandler

    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Event viewOversigtRowDeleting As viewOversigtRowChangeEventHandler

    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Event viewOversigtRowDeleted As viewOversigtRowChangeEventHandler

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Overloads Sub AddviewOversigtRow(ByVal row As viewOversigtRow)
      Me.Rows.Add(row)
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Overloads Function AddviewOversigtRow( _
                    ByVal MedieplanNr As Integer, _
                    ByVal Version As Short, _
                    ByVal AnnoncørNo_ As String, _
                    ByVal BureauNo_ As String, _
                    ByVal Format As String, _
                    ByVal AntalFarver As Byte, _
                    ByVal IndrykningsUge As Byte, _
                    ByVal OrdreUdsendt As String, _
                    ByVal MaterialeFra As String, _
                    ByVal MaterialeUdsendt As String, _
                    ByVal OrdreAnsvarlig As String, _
                    ByVal SalgsAnsvarlig As String, _
                    ByVal Nr As String, _
                    ByVal Overskrift As String, _
                    ByVal Deadline As String, _
                    ByVal Kommentar As String) As viewOversigtRow
      Dim rowviewOversigtRow As viewOversigtRow = CType(Me.NewRow, viewOversigtRow)
      Dim columnValuesArray() As Object = New Object() {MedieplanNr, Version, AnnoncørNo_, BureauNo_, Format, AntalFarver, IndrykningsUge, OrdreUdsendt, MaterialeFra, MaterialeUdsendt, OrdreAnsvarlig, SalgsAnsvarlig, Nr, Overskrift, Deadline, Kommentar}
      rowviewOversigtRow.ItemArray = columnValuesArray
      Me.Rows.Add(rowviewOversigtRow)
      Return rowviewOversigtRow
    End Function

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Overrides Function Clone() As Global.System.Data.DataTable
      Dim cln As viewOversigtDataTable = CType(MyBase.Clone, viewOversigtDataTable)
      cln.InitVars()
      Return cln
    End Function

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Protected Overrides Function CreateInstance() As Global.System.Data.DataTable
      Return New viewOversigtDataTable()
    End Function

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Friend Sub InitVars()
      Me.columnMedieplanNr = MyBase.Columns("MedieplanNr")
      Me.columnVersion = MyBase.Columns("Version")
      Me.columnAnnoncørNo_ = MyBase.Columns("AnnoncørNo_")
      Me.columnBureauNo_ = MyBase.Columns("BureauNo_")
      Me.columnFormat = MyBase.Columns("Format")
      Me.columnAntalFarver = MyBase.Columns("AntalFarver")
      Me.columnIndrykningsUge = MyBase.Columns("IndrykningsUge")
      Me.columnOrdreUdsendt = MyBase.Columns("OrdreUdsendt")
      Me.columnMaterialeFra = MyBase.Columns("MaterialeFra")
      Me.columnMaterialeUdsendt = MyBase.Columns("MaterialeUdsendt")
      Me.columnOrdreAnsvarlig = MyBase.Columns("OrdreAnsvarlig")
      Me.columnSalgsAnsvarlig = MyBase.Columns("SalgsAnsvarlig")
      Me.columnNr = MyBase.Columns("Nr")
      Me.columnOverskrift = MyBase.Columns("Overskrift")
      Me.columnDeadline = MyBase.Columns("Deadline")
      Me.columnKommentar = MyBase.Columns("Kommentar")
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Private Sub InitClass()
      Me.columnMedieplanNr = New Global.System.Data.DataColumn("MedieplanNr", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
      MyBase.Columns.Add(Me.columnMedieplanNr)
      Me.columnVersion = New Global.System.Data.DataColumn("Version", GetType(Short), Nothing, Global.System.Data.MappingType.Element)
      MyBase.Columns.Add(Me.columnVersion)
      Me.columnAnnoncørNo_ = New Global.System.Data.DataColumn("AnnoncørNo_", GetType(String), Nothing, Global.System.Data.MappingType.Element)
      MyBase.Columns.Add(Me.columnAnnoncørNo_)
      Me.columnBureauNo_ = New Global.System.Data.DataColumn("BureauNo_", GetType(String), Nothing, Global.System.Data.MappingType.Element)
      MyBase.Columns.Add(Me.columnBureauNo_)
      Me.columnFormat = New Global.System.Data.DataColumn("Format", GetType(String), Nothing, Global.System.Data.MappingType.Element)
      MyBase.Columns.Add(Me.columnFormat)
      Me.columnAntalFarver = New Global.System.Data.DataColumn("AntalFarver", GetType(Byte), Nothing, Global.System.Data.MappingType.Element)
      MyBase.Columns.Add(Me.columnAntalFarver)
      Me.columnIndrykningsUge = New Global.System.Data.DataColumn("IndrykningsUge", GetType(Byte), Nothing, Global.System.Data.MappingType.Element)
      MyBase.Columns.Add(Me.columnIndrykningsUge)
      Me.columnOrdreUdsendt = New Global.System.Data.DataColumn("OrdreUdsendt", GetType(String), Nothing, Global.System.Data.MappingType.Element)
      MyBase.Columns.Add(Me.columnOrdreUdsendt)
      Me.columnMaterialeFra = New Global.System.Data.DataColumn("MaterialeFra", GetType(String), Nothing, Global.System.Data.MappingType.Element)
      MyBase.Columns.Add(Me.columnMaterialeFra)
      Me.columnMaterialeUdsendt = New Global.System.Data.DataColumn("MaterialeUdsendt", GetType(String), Nothing, Global.System.Data.MappingType.Element)
      MyBase.Columns.Add(Me.columnMaterialeUdsendt)
      Me.columnOrdreAnsvarlig = New Global.System.Data.DataColumn("OrdreAnsvarlig", GetType(String), Nothing, Global.System.Data.MappingType.Element)
      MyBase.Columns.Add(Me.columnOrdreAnsvarlig)
      Me.columnSalgsAnsvarlig = New Global.System.Data.DataColumn("SalgsAnsvarlig", GetType(String), Nothing, Global.System.Data.MappingType.Element)
      MyBase.Columns.Add(Me.columnSalgsAnsvarlig)
      Me.columnNr = New Global.System.Data.DataColumn("Nr", GetType(String), Nothing, Global.System.Data.MappingType.Element)
      MyBase.Columns.Add(Me.columnNr)
      Me.columnOverskrift = New Global.System.Data.DataColumn("Overskrift", GetType(String), Nothing, Global.System.Data.MappingType.Element)
      MyBase.Columns.Add(Me.columnOverskrift)
      Me.columnDeadline = New Global.System.Data.DataColumn("Deadline", GetType(String), Nothing, Global.System.Data.MappingType.Element)
      MyBase.Columns.Add(Me.columnDeadline)
      Me.columnKommentar = New Global.System.Data.DataColumn("Kommentar", GetType(String), Nothing, Global.System.Data.MappingType.Element)
      MyBase.Columns.Add(Me.columnKommentar)
      Me.columnMedieplanNr.AllowDBNull = False
      Me.columnVersion.AllowDBNull = False
      Me.columnAnnoncørNo_.MaxLength = 30
      Me.columnBureauNo_.MaxLength = 30
      Me.columnFormat.ReadOnly = True
      Me.columnFormat.MaxLength = 23
      Me.columnAntalFarver.AllowDBNull = False
      Me.columnIndrykningsUge.AllowDBNull = False
      Me.columnOrdreUdsendt.AllowDBNull = False
      Me.columnOrdreUdsendt.ReadOnly = True
      Me.columnOrdreUdsendt.MaxLength = 3
      Me.columnMaterialeFra.ReadOnly = True
      Me.columnMaterialeFra.MaxLength = 30
      Me.columnMaterialeUdsendt.ReadOnly = True
      Me.columnMaterialeUdsendt.MaxLength = 32
      Me.columnOrdreAnsvarlig.AllowDBNull = False
      Me.columnOrdreAnsvarlig.MaxLength = 10
      Me.columnSalgsAnsvarlig.ReadOnly = True
      Me.columnSalgsAnsvarlig.MaxLength = 10
      Me.columnNr.ReadOnly = True
      Me.columnNr.MaxLength = 21
      Me.columnOverskrift.AllowDBNull = False
      Me.columnOverskrift.MaxLength = 30
      Me.columnDeadline.MaxLength = 16
      Me.columnKommentar.AllowDBNull = False
      Me.columnKommentar.MaxLength = 250
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Function NewviewOversigtRow() As viewOversigtRow
      Return CType(Me.NewRow, viewOversigtRow)
    End Function

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Protected Overrides Function NewRowFromBuilder(ByVal builder As Global.System.Data.DataRowBuilder) As Global.System.Data.DataRow
      Return New viewOversigtRow(builder)
    End Function

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Protected Overrides Function GetRowType() As Global.System.Type
      Return GetType(viewOversigtRow)
    End Function

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Protected Overrides Sub OnRowChanged(ByVal e As Global.System.Data.DataRowChangeEventArgs)
      MyBase.OnRowChanged(e)
      If (Not (Me.viewOversigtRowChangedEvent) Is Nothing) Then
        RaiseEvent viewOversigtRowChanged(Me, New viewOversigtRowChangeEvent(CType(e.Row, viewOversigtRow), e.Action))
      End If
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Protected Overrides Sub OnRowChanging(ByVal e As Global.System.Data.DataRowChangeEventArgs)
      MyBase.OnRowChanging(e)
      If (Not (Me.viewOversigtRowChangingEvent) Is Nothing) Then
        RaiseEvent viewOversigtRowChanging(Me, New viewOversigtRowChangeEvent(CType(e.Row, viewOversigtRow), e.Action))
      End If
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Protected Overrides Sub OnRowDeleted(ByVal e As Global.System.Data.DataRowChangeEventArgs)
      MyBase.OnRowDeleted(e)
      If (Not (Me.viewOversigtRowDeletedEvent) Is Nothing) Then
        RaiseEvent viewOversigtRowDeleted(Me, New viewOversigtRowChangeEvent(CType(e.Row, viewOversigtRow), e.Action))
      End If
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Protected Overrides Sub OnRowDeleting(ByVal e As Global.System.Data.DataRowChangeEventArgs)
      MyBase.OnRowDeleting(e)
      If (Not (Me.viewOversigtRowDeletingEvent) Is Nothing) Then
        RaiseEvent viewOversigtRowDeleting(Me, New viewOversigtRowChangeEvent(CType(e.Row, viewOversigtRow), e.Action))
      End If
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Sub RemoveviewOversigtRow(ByVal row As viewOversigtRow)
      Me.Rows.Remove(row)
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Shared Function GetTypedTableSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
      Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType()
      Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence()
      Dim ds As dstOversigt = New dstOversigt()
      Dim any1 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
      any1.Namespace = "http://www.w3.org/2001/XMLSchema"
      any1.MinOccurs = New Decimal(0)
      any1.MaxOccurs = Decimal.MaxValue
      any1.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
      sequence.Items.Add(any1)
      Dim any2 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
      any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
      any2.MinOccurs = New Decimal(1)
      any2.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
      sequence.Items.Add(any2)
      Dim attribute1 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute()
      attribute1.Name = "namespace"
      attribute1.FixedValue = ds.Namespace
      type.Attributes.Add(attribute1)
      Dim attribute2 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute()
      attribute2.Name = "tableTypeName"
      attribute2.FixedValue = "viewOversigtDataTable"
      type.Attributes.Add(attribute2)
      type.Particle = sequence
      Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
      If xs.Contains(dsSchema.TargetNamespace) Then
        Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
        Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
        Try
          Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
          dsSchema.Write(s1)
          Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
          Do While schemas.MoveNext
            schema = CType(schemas.Current, Global.System.Xml.Schema.XmlSchema)
            s2.SetLength(0)
            schema.Write(s2)
            If (s1.Length = s2.Length) Then
              s1.Position = 0
              s2.Position = 0

              Do While ((s1.Position <> s1.Length) _
                          AndAlso (s1.ReadByte = s2.ReadByte))


              Loop
              If (s1.Position = s1.Length) Then
                Return type
              End If
            End If

          Loop
        Finally
          If (Not (s1) Is Nothing) Then
            s1.Close()
          End If
          If (Not (s2) Is Nothing) Then
            s2.Close()
          End If
        End Try
      End If
      xs.Add(dsSchema)
      Return type
    End Function
  End Class

  '''<summary>
  '''Represents strongly named DataRow class.
  '''</summary>
  Partial Public Class viewOversigtRow
    Inherits Global.System.Data.DataRow

    Private tableviewOversigt As viewOversigtDataTable

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Friend Sub New(ByVal rb As Global.System.Data.DataRowBuilder)
      MyBase.New(rb)
      Me.tableviewOversigt = CType(Me.Table, viewOversigtDataTable)
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Property MedieplanNr() As Integer
      Get
        Return CType(Me(Me.tableviewOversigt.MedieplanNrColumn), Integer)
      End Get
      Set(value As Integer)
        Me(Me.tableviewOversigt.MedieplanNrColumn) = value
      End Set
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Property Version() As Short
      Get
        Return CType(Me(Me.tableviewOversigt.VersionColumn), Short)
      End Get
      Set(value As Short)
        Me(Me.tableviewOversigt.VersionColumn) = value
      End Set
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Property AnnoncørNo_() As String
      Get
        If Me.IsAnnoncørNo_Null Then
          Return String.Empty
        Else
          Return CType(Me(Me.tableviewOversigt.AnnoncørNo_Column), String)
        End If
      End Get
      Set(value As String)
        Me(Me.tableviewOversigt.AnnoncørNo_Column) = value
      End Set
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Property BureauNo_() As String
      Get
        If Me.IsBureauNo_Null Then
          Return String.Empty
        Else
          Return CType(Me(Me.tableviewOversigt.BureauNo_Column), String)
        End If
      End Get
      Set(value As String)
        Me(Me.tableviewOversigt.BureauNo_Column) = value
      End Set
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Property Format() As String
      Get
        Try
          Return CType(Me(Me.tableviewOversigt.FormatColumn), String)
        Catch e As Global.System.InvalidCastException
          Throw New Global.System.Data.StrongTypingException("The value for column 'Format' in table 'viewOversigt' is DBNull.", e)
        End Try
      End Get
      Set(value As String)
        Me(Me.tableviewOversigt.FormatColumn) = value
      End Set
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Property AntalFarver() As Byte
      Get
        Return CType(Me(Me.tableviewOversigt.AntalFarverColumn), Byte)
      End Get
      Set(value As Byte)
        Me(Me.tableviewOversigt.AntalFarverColumn) = value
      End Set
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Property IndrykningsUge() As Byte
      Get
        Return CType(Me(Me.tableviewOversigt.IndrykningsUgeColumn), Byte)
      End Get
      Set(value As Byte)
        Me(Me.tableviewOversigt.IndrykningsUgeColumn) = value
      End Set
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Property OrdreUdsendt() As String
      Get
        Return CType(Me(Me.tableviewOversigt.OrdreUdsendtColumn), String)
      End Get
      Set(value As String)
        Me(Me.tableviewOversigt.OrdreUdsendtColumn) = value
      End Set
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Property MaterialeFra() As String
      Get
        Try
          Return CType(Me(Me.tableviewOversigt.MaterialeFraColumn), String)
        Catch e As Global.System.InvalidCastException
          Throw New Global.System.Data.StrongTypingException("The value for column 'MaterialeFra' in table 'viewOversigt' is DBNull.", e)
        End Try
      End Get
      Set(value As String)
        Me(Me.tableviewOversigt.MaterialeFraColumn) = value
      End Set
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Property MaterialeUdsendt() As String
      Get
        Try
          Return CType(Me(Me.tableviewOversigt.MaterialeUdsendtColumn), String)
        Catch e As Global.System.InvalidCastException
          Throw New Global.System.Data.StrongTypingException("The value for column 'MaterialeUdsendt' in table 'viewOversigt' is DBNull.", e)
        End Try
      End Get
      Set(value As String)
        Me(Me.tableviewOversigt.MaterialeUdsendtColumn) = value
      End Set
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Property OrdreAnsvarlig() As String
      Get
        Return CType(Me(Me.tableviewOversigt.OrdreAnsvarligColumn), String)
      End Get
      Set(value As String)
        Me(Me.tableviewOversigt.OrdreAnsvarligColumn) = value
      End Set
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Property SalgsAnsvarlig() As String
      Get
        Try
          Return CType(Me(Me.tableviewOversigt.SalgsAnsvarligColumn), String)
        Catch e As Global.System.InvalidCastException
          Throw New Global.System.Data.StrongTypingException("The value for column 'SalgsAnsvarlig' in table 'viewOversigt' is DBNull.", e)
        End Try
      End Get
      Set(value As String)
        Me(Me.tableviewOversigt.SalgsAnsvarligColumn) = value
      End Set
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Property Nr() As String
      Get
        Try
          Return CType(Me(Me.tableviewOversigt.NrColumn), String)
        Catch e As Global.System.InvalidCastException
          Throw New Global.System.Data.StrongTypingException("The value for column 'Nr' in table 'viewOversigt' is DBNull.", e)
        End Try
      End Get
      Set(value As String)
        Me(Me.tableviewOversigt.NrColumn) = value
      End Set
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Property Overskrift() As String
      Get
        Return CType(Me(Me.tableviewOversigt.OverskriftColumn), String)
      End Get
      Set(value As String)
        Me(Me.tableviewOversigt.OverskriftColumn) = value
      End Set
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Property Deadline() As String
      Get
        Try
          Return CType(Me(Me.tableviewOversigt.DeadlineColumn), String)
        Catch e As Global.System.InvalidCastException
          Throw New Global.System.Data.StrongTypingException("The value for column 'Deadline' in table 'viewOversigt' is DBNull.", e)
        End Try
      End Get
      Set(value As String)
        Me(Me.tableviewOversigt.DeadlineColumn) = value
      End Set
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Property Kommentar() As String
      Get
        Return CType(Me(Me.tableviewOversigt.KommentarColumn), String)
      End Get
      Set(value As String)
        Me(Me.tableviewOversigt.KommentarColumn) = value
      End Set
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Function IsAnnoncørNo_Null() As Boolean
      Return Me.IsNull(Me.tableviewOversigt.AnnoncørNo_Column)
    End Function

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Sub SetAnnoncørNo_Null()
      Me(Me.tableviewOversigt.AnnoncørNo_Column) = Global.System.Convert.DBNull
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Function IsBureauNo_Null() As Boolean
      Return Me.IsNull(Me.tableviewOversigt.BureauNo_Column)
    End Function

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Sub SetBureauNo_Null()
      Me(Me.tableviewOversigt.BureauNo_Column) = Global.System.Convert.DBNull
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Function IsFormatNull() As Boolean
      Return Me.IsNull(Me.tableviewOversigt.FormatColumn)
    End Function

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Sub SetFormatNull()
      Me(Me.tableviewOversigt.FormatColumn) = Global.System.Convert.DBNull
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Function IsMaterialeFraNull() As Boolean
      Return Me.IsNull(Me.tableviewOversigt.MaterialeFraColumn)
    End Function

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Sub SetMaterialeFraNull()
      Me(Me.tableviewOversigt.MaterialeFraColumn) = Global.System.Convert.DBNull
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Function IsMaterialeUdsendtNull() As Boolean
      Return Me.IsNull(Me.tableviewOversigt.MaterialeUdsendtColumn)
    End Function

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Sub SetMaterialeUdsendtNull()
      Me(Me.tableviewOversigt.MaterialeUdsendtColumn) = Global.System.Convert.DBNull
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Function IsSalgsAnsvarligNull() As Boolean
      Return Me.IsNull(Me.tableviewOversigt.SalgsAnsvarligColumn)
    End Function

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Sub SetSalgsAnsvarligNull()
      Me(Me.tableviewOversigt.SalgsAnsvarligColumn) = Global.System.Convert.DBNull
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Function IsNrNull() As Boolean
      Return Me.IsNull(Me.tableviewOversigt.NrColumn)
    End Function

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Sub SetNrNull()
      Me(Me.tableviewOversigt.NrColumn) = Global.System.Convert.DBNull
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Function IsDeadlineNull() As Boolean
      Return Me.IsNull(Me.tableviewOversigt.DeadlineColumn)
    End Function

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Sub SetDeadlineNull()
      Me(Me.tableviewOversigt.DeadlineColumn) = Global.System.Convert.DBNull
    End Sub
  End Class

  '''<summary>
  '''Row event argument class
  '''</summary>
  <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
  Public Class viewOversigtRowChangeEvent
    Inherits Global.System.EventArgs

    Private eventRow As viewOversigtRow

    Private eventAction As Global.System.Data.DataRowAction

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Sub New(ByVal row As viewOversigtRow, ByVal action As Global.System.Data.DataRowAction)
      MyBase.New()
      Me.eventRow = row
      Me.eventAction = action
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public ReadOnly Property Row() As viewOversigtRow
      Get
        Return Me.eventRow
      End Get
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public ReadOnly Property Action() As Global.System.Data.DataRowAction
      Get
        Return Me.eventAction
      End Get
    End Property
  End Class
End Class

Namespace dstOversigtTableAdapters

  '''<summary>
  '''Represents the connection and commands used to retrieve and save data.
  '''</summary>
  <Global.System.ComponentModel.DesignerCategoryAttribute("code"), _
   Global.System.ComponentModel.ToolboxItem(True), _
   Global.System.ComponentModel.DataObjectAttribute(True), _
   Global.System.ComponentModel.DesignerAttribute("Microsoft.VSDesigner.DataSource.Design.TableAdapterDesigner, Microsoft.VSDesigner" & _
      ", Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"), _
   Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")> _
  Partial Public Class viewOversigtTableAdapter
    Inherits Global.System.ComponentModel.Component

    Private WithEvents _adapter As Global.System.Data.SqlClient.SqlDataAdapter

    Private _connection As Global.System.Data.SqlClient.SqlConnection

    Private _commandCollection() As Global.System.Data.SqlClient.SqlCommand

    Private _clearBeforeFill As Boolean

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Sub New()
      MyBase.New()
      Me.ClearBeforeFill = True
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Private ReadOnly Property Adapter() As Global.System.Data.SqlClient.SqlDataAdapter
      Get
        If (Me._adapter Is Nothing) Then
          Me.InitAdapter()
        End If
        Return Me._adapter
      End Get
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Friend Property Connection() As Global.System.Data.SqlClient.SqlConnection
      Get
        If (Me._connection Is Nothing) Then
          Me.InitConnection()
        End If
        Return Me._connection
      End Get
      Set(value As Global.System.Data.SqlClient.SqlConnection)
        Me._connection = value
        If (Not (Me.Adapter.InsertCommand) Is Nothing) Then
          Me.Adapter.InsertCommand.Connection = value
        End If
        If (Not (Me.Adapter.DeleteCommand) Is Nothing) Then
          Me.Adapter.DeleteCommand.Connection = value
        End If
        If (Not (Me.Adapter.UpdateCommand) Is Nothing) Then
          Me.Adapter.UpdateCommand.Connection = value
        End If
        Dim i As Integer = 0
        Do While (i < Me.CommandCollection.Length)
          If (Not (Me.CommandCollection(i)) Is Nothing) Then
            CType(Me.CommandCollection(i), Global.System.Data.SqlClient.SqlCommand).Connection = value
          End If
          i = (i + 1)
        Loop
      End Set
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Protected ReadOnly Property CommandCollection() As Global.System.Data.SqlClient.SqlCommand()
      Get
        If (Me._commandCollection Is Nothing) Then
          Me.InitCommandCollection()
        End If
        Return Me._commandCollection
      End Get
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Property ClearBeforeFill() As Boolean
      Get
        Return Me._clearBeforeFill
      End Get
      Set(value As Boolean)
        Me._clearBeforeFill = value
      End Set
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Private Sub InitAdapter()
      Me._adapter = New Global.System.Data.SqlClient.SqlDataAdapter()
      Dim tableMapping As Global.System.Data.Common.DataTableMapping = New Global.System.Data.Common.DataTableMapping()
      tableMapping.SourceTable = "Table"
      tableMapping.DataSetTable = "viewOversigt"
      tableMapping.ColumnMappings.Add("MedieplanNr", "MedieplanNr")
      tableMapping.ColumnMappings.Add("Version", "Version")
      tableMapping.ColumnMappings.Add("AnnoncørNo_", "AnnoncørNo_")
      tableMapping.ColumnMappings.Add("BureauNo_", "BureauNo_")
      tableMapping.ColumnMappings.Add("Format", "Format")
      tableMapping.ColumnMappings.Add("AntalFarver", "AntalFarver")
      tableMapping.ColumnMappings.Add("IndrykningsUge", "IndrykningsUge")
      tableMapping.ColumnMappings.Add("OrdreUdsendt", "OrdreUdsendt")
      tableMapping.ColumnMappings.Add("MaterialeFra", "MaterialeFra")
      tableMapping.ColumnMappings.Add("MaterialeUdsendt", "MaterialeUdsendt")
      tableMapping.ColumnMappings.Add("OrdreAnsvarlig", "OrdreAnsvarlig")
      tableMapping.ColumnMappings.Add("SalgsAnsvarlig", "SalgsAnsvarlig")
      tableMapping.ColumnMappings.Add("Nr", "Nr")
      tableMapping.ColumnMappings.Add("Overskrift", "Overskrift")
      tableMapping.ColumnMappings.Add("Deadline", "Deadline")
      tableMapping.ColumnMappings.Add("Kommentar", "Kommentar")
      Me._adapter.TableMappings.Add(tableMapping)
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Private Sub InitConnection()
      Me._connection = New Global.System.Data.SqlClient.SqlConnection()
      Me._connection.ConnectionString = Global.WinPlanner.My.MySettings.Default.DiMPdotNetConnectionString
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Private Sub InitCommandCollection()
      Me._commandCollection = New Global.System.Data.SqlClient.SqlCommand(1) {}
      Me._commandCollection(0) = New Global.System.Data.SqlClient.SqlCommand()
      Me._commandCollection(0).Connection = Me.Connection
      Me._commandCollection(0).CommandText = "SELECT        CASE WHEN viewOversigt.Version < 10 THEN LTRIM(STR(viewOversigt.Med" & _
          "ieplanNr)) + '-' + LTRIM(STR(viewOversigt.Version)) WHEN viewOversigt.Version > " & _
          "10 AND" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "                          viewOversigt.Version < 100 THEN LTRIM(STR(view" & _
          "Oversigt.MedieplanNr)) + '-' + RIGHT(LTRIM(viewOversigt.Version / 10), 1) " & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "    " & _
          "                     + '-' + RIGHT(LTRIM(viewOversigt.Version), 1) WHEN viewOver" & _
          "sigt.Version > 100 THEN LTRIM(STR(viewOversigt.MedieplanNr)) " & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "                 " & _
          "        + '-' + RIGHT(LTRIM(viewOversigt.Version / 100), 1) + '-' + RIGHT(LTRIM(" & _
          "viewOversigt.Version / 10), 1) + '-' + RIGHT(LTRIM(viewOversigt.Version), 1) END" & _
          " AS Nr, " & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "                         viewOversigt.MedieplanNr, viewOversigt.Versio" & _
          "n," & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "                             (SELECT        Name" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "                          " & _
          "     FROM            NavisionContact" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "                               WHERE      " & _
          "  (No_ = viewOversigt.AnnoncørNo_)) AS AnnoncørNo_," & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "                           " & _
          "  (SELECT        Name" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "                               FROM            NavisionCo" & _
          "ntact AS NavisionContact_1" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "                               WHERE        (No_ = v" & _
          "iewOversigt.BureauNo_)) AS BureauNo_, viewOversigt.Format, viewOversigt.AntalFar" & _
          "ver, viewOversigt.IndrykningsUge, " & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "                         viewOversigt.OrdreU" & _
          "dsendt, viewOversigt.MaterialeFra, viewOversigt.MaterialeUdsendt, viewOversigt.K" & _
          "onsulentCode AS OrdreAnsvarlig," & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "                             (SELECT        [Sa" & _
          "lesperson Code]" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "                               FROM            NavisionContact " & _
          "AS NavisionContact_2" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "                               WHERE        (No_ = viewOve" & _
          "rsigt.AnnoncørNo_)) AS SalgsAnsvarlig, viewOversigt.Overskrift, viewOversigt.Dea" & _
          "dline, tblMedieplanNr.Kommentar" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "FROM            viewOversigt INNER JOIN" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "      " & _
          "                   tblMedieplanNr ON viewOversigt.MedieplanNr = tblMedieplanNr.M" & _
          "edieplanNr"
      Me._commandCollection(0).CommandType = Global.System.Data.CommandType.Text
      Me._commandCollection(1) = New Global.System.Data.SqlClient.SqlCommand()
      Me._commandCollection(1).Connection = Me.Connection
      Me._commandCollection(1).CommandText = "SELECT        (SELECT        Name" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "                          FROM            Navi" & _
          "sionContact" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "                          WHERE        (No_ = viewOversigt.Annoncør" & _
          "No_)) AS AnnoncørNo_, viewOversigt.AntalFarver," & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "                             (S" & _
          "ELECT        Name" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "                               FROM            NavisionContac" & _
          "t AS NavisionContact_1" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "                               WHERE        (No_ = viewO" & _
          "versigt.BureauNo_)) AS BureauNo_, viewOversigt.Format, viewOversigt.IndrykningsU" & _
          "ge, viewOversigt.KonsulentCode AS OrdreAnsvarlig, " & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "                         vie" & _
          "wOversigt.MaterialeFra, viewOversigt.MaterialeUdsendt, viewOversigt.MedieplanNr," & _
          " " & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "                         CASE WHEN viewOversigt.Version < 10 THEN LTRIM(STR(v" & _
          "iewOversigt.MedieplanNr)) + '-' + LTRIM(STR(viewOversigt.Version)) WHEN viewOver" & _
          "sigt.Version > 10 AND" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "                          viewOversigt.Version < 100 THEN" & _
          " LTRIM(STR(viewOversigt.MedieplanNr)) + '-' + RIGHT(LTRIM(viewOversigt.Version /" & _
          " 10), 1) " & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "                         + '-' + RIGHT(LTRIM(viewOversigt.Version), 1" & _
          ") WHEN viewOversigt.Version > 100 THEN LTRIM(STR(viewOversigt.MedieplanNr)) " & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "  " & _
          "                       + '-' + RIGHT(LTRIM(viewOversigt.Version / 100), 1) + '-'" & _
          " + RIGHT(LTRIM(viewOversigt.Version / 10), 1) + '-' + RIGHT(LTRIM(viewOversigt.V" & _
          "ersion), 1) END AS Nr, " & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "                         viewOversigt.OrdreUdsendt, vie" & _
          "wOversigt.Overskrift," & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "                             (SELECT        [Salesperson " & _
          "Code]" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "                               FROM            NavisionContact AS Navisio" & _
          "nContact_2" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "                               WHERE        (No_ = viewOversigt.Anno" & _
          "ncørNo_)) AS SalgsAnsvarlig, viewOversigt.Version, viewOversigt.Deadline, tblMed" & _
          "ieplanNr.Kommentar" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "FROM            viewOversigt INNER JOIN" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "                   " & _
          "      tblMedieplanNr ON viewOversigt.MedieplanNr = tblMedieplanNr.MedieplanNr" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "W" & _
          "HERE        (viewOversigt.IndrykningsUge BETWEEN @UgeStart AND @UgeSlut)" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "ORDER " & _
          "BY viewOversigt.IndrykningsUge"
      Me._commandCollection(1).CommandType = Global.System.Data.CommandType.Text
      Me._commandCollection(1).Parameters.Add(New Global.System.Data.SqlClient.SqlParameter("@UgeStart", Global.System.Data.SqlDbType.TinyInt, 1, Global.System.Data.ParameterDirection.Input, 0, 0, "IndrykningsUge", Global.System.Data.DataRowVersion.Current, False, Nothing, "", "", ""))
      Me._commandCollection(1).Parameters.Add(New Global.System.Data.SqlClient.SqlParameter("@UgeSlut", Global.System.Data.SqlDbType.TinyInt, 1, Global.System.Data.ParameterDirection.Input, 0, 0, "IndrykningsUge", Global.System.Data.DataRowVersion.Current, False, Nothing, "", "", ""))
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"), _
     Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter"), _
     Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.Fill, True)> _
    Public Overridable Overloads Function Fill(ByVal dataTable As dstOversigt.viewOversigtDataTable) As Integer
      Me.Adapter.SelectCommand = Me.CommandCollection(0)
      If (Me.ClearBeforeFill = True) Then
        dataTable.Clear()
      End If
      Dim returnValue As Integer = Me.Adapter.Fill(dataTable)
      Return returnValue
    End Function

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"), _
     Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter"), _
     Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.Fill, False)> _
    Public Overridable Overloads Function FillByUger(ByVal dataTable As dstOversigt.viewOversigtDataTable, ByVal UgeStart As Byte, ByVal UgeSlut As Byte) As Integer
      Me.Adapter.SelectCommand = Me.CommandCollection(1)
      Me.Adapter.SelectCommand.Parameters(0).Value = CType(UgeStart, Byte)
      Me.Adapter.SelectCommand.Parameters(1).Value = CType(UgeSlut, Byte)
      If (Me.ClearBeforeFill = True) Then
        dataTable.Clear()
      End If
      Dim returnValue As Integer = Me.Adapter.Fill(dataTable)
      Return returnValue
    End Function
  End Class
End Namespace
